"""
SQLAlchemy model for Slide entity.
"""

from sqlalchemy import Column, String, Text, Integer, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.data.models.base import Base


class SlideModel(Base):
    __tablename__ = "slides"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    deck_id = Column(
        UUID(as_uuid=True), ForeignKey("decks.id"), nullable=False, index=True
    )
    order = Column(Integer, nullable=False)
    title = Column(String(500), nullable=False)
    content_outline = Column(Text, nullable=False)
    html_content = Column(Text, nullable=True)  # Generated by LLM
    presenter_notes = Column(Text, nullable=True)
    template_type = Column(String(50), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, onupdate=datetime.utcnow)

    # Relationships
    deck = relationship("DeckModel", back_populates="slides")
